Core integration
liveview-native/liveview-native-core-jetpack pull request #1
Opened 2023-03-23 11:09 UTC by Kashif-E

This contains an android and a rust project. The rust project contains jni wrapper for the core and has the core integrated as a library. The android project uses[ mozilla gradle plugin](https://github.com/mozilla/rust-android-gradle) to generate .so files and the maven plugin is used for publishing the android library to jitpack.io which then can be used with the jetpack client

2023-03-24 19:22 UTC, KronicDeth requested changes

2023-03-24 19:22 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Attribute.kt
> +        get() = _name ?: get_name(nativeObject).also { _name = it }
You can use lazy initialization for this

```suggestion
    val name: String by lazy {
      get_name(nativeObject)
    }
```

2023-03-24 19:22 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Attribute.kt
> +        get() = _namespace ?: get_namespace(nativeObject).also { _namespace = it }
You can use lazy initialization for this

```suggestion
    /** The namespace of an attribute */
    val namespace by lazy {
        get_namespace(nativeObject)
    }
```

2023-03-24 19:22 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Attribute.kt
> +        get() = _val ?: get_value(nativeObject).also { _val = it }
You can use lazy initialization for this

```suggestion
    val value by lazy {
        get_value(nativeObject)
     }
```

2023-03-24 19:22 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Attribute.kt
> +    }
Use expression form and break the string on the `\n` to make the code match the printed form to make it easier to read what would be printed. I also added 2 spaces to indent the fields when printed.

```suggestion
    override fun toString(): String =
      "Attribute {\n"+
      "  Name: ${name.ifEmpty { "None" }}\n" +
      "  Namespace: ${namespace.ifEmpty { "None" }}\n" +
      "  Value: ${value.ifEmpty { "None" }}\n" +
      "}"
```

2023-03-24 19:22 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Document.kt
> +        enum class ChangeType {
Leave a blank line between the `fun` and `enum class`

```suggestion
        private external fun initialize_log()
        
        enum class ChangeType {
```

2023-03-24 19:22 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Document.kt
> +    }
Use expression form

```suggestion
    fun getNodeString(nodeRef: NodeRef): String = node_to_string(nativeObject, nodeRef.ref)
```

2023-03-24 19:22 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Document.kt
> +        }
Include the node type in the error in case a node type is added later and this code is not updated

```suggestion
        return when (val nodeType = get_node_type(nodePtr)) {
            0.toByte() -> {
                Node.Root
            }
            1.toByte() -> {
                // element
                val elementPtr = get_node_element(nodePtr)
                val namespace = get_node_element_namespace(elementPtr)
                val tag = get_node_element_tag(elementPtr)
                val attributes = get_node_element_attributes(elementPtr)
                Node.Element(namespace, tag, attributes).also { it.nativeObject = elementPtr }
            }
            2.toByte() -> {
                Node.Leaf(get_node_leaf_string(nativeObject, nodeRef.ref))
            }
            else -> throw Exception("Unknown node type ${nodeType}")
        }
```

2023-03-24 19:22 UTC, KronicDeth commented on jitpack.yml
> +  - yes | sdkmanager --uninstall "ndk-bundle" | sdkmanager --install "ndk;21.4.7075529"
❤️ how did you figure out the default bundle was the problem?

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_00024Companion_initialize_1log<
Where does the `00024` come from and can it change?

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let node = u32::try_from(node).expect("value beyond `u32` range");
If a negative `jint` is passed this will `panic`.  I don't see any `panic::catch_unwind`, so how is the Rust Panic being converted to a Java Exception?

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +use android_logger::Config;
I don't see any `panic::catch_unwind` in this file, so are Rust panics converted automatically to Java exceptions with some wrapper that is automated?  Without that conversion the Rust panic will crash the JVM.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let dom = unsafe { jlong_to_pointer::<dom::Document>(this).as_ref().unwrap() };
This can panic if `null` (`0`) is passed in.   It needs to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +        let dom: &dom::Document = jlong_to_pointer::<dom::Document>(this).as_ref().unwrap();
This can panic if `null` (`0`) is passed in.   It needs to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let node = u32::try_from(node_ref).expect("value beyond `u32` range");
a negative `node_ref` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let dom = unsafe { jlong_to_pointer::<dom::Document>(this).as_ref().unwrap() };
A negative or 0 `this` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let node = u32::try_from(node_ref).expect("value beyond `u32` range");
A negative `node_ref` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let doc = unsafe { jlong_to_pointer::<dom::Document>(this).as_ref().unwrap() };
A negative or 0 `this` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +        let node: &Node = jlong_to_pointer::<Node>(node).as_ref().unwrap();
A negative or 0 `node` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +        let node: *mut Node = jlong_to_pointer::<Node>(node).as_mut().unwrap();
A negative or 0 `node` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +        let dom: *mut Element = jlong_to_pointer::<Element>(this).as_mut().unwrap();
A negative or 0 `this` would cause this to panic that would need to be converted to a Java Exception

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +        let element: &Element = jlong_to_pointer::<Element>(element).as_mut().unwrap();
A negative or 0 `element` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let element: &Element = unsafe { jlong_to_pointer::<Element>(element).as_mut().unwrap() };
A negative or 0 `element` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let element: &Element = unsafe { jlong_to_pointer::<Element>(element).as_mut().unwrap() };
A negative or 0 `element` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +        .expect("No such class");
This panic needs to be converted to a `NoClassDefFoundError`Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +        let dom: *mut Attribute = jlong_to_pointer::<Attribute>(this).as_mut().unwrap();
A negative or 0 `this` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let attribute: &Attribute = unsafe { jlong_to_pointer::<Attribute>(attr).as_mut().unwrap() };
A negative or 0 `attr` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let attribute: &Attribute = unsafe { jlong_to_pointer::<Attribute>(attr).as_ref().unwrap() };
A negative or 0 `attr` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let attribute: &Attribute = unsafe { jlong_to_pointer::<Attribute>(attr).as_ref().unwrap() };
A negative or 0 `attr` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let node = u32::try_from(node_ref).expect("value beyond `u32` range");
A negative `node_ref` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let dom = unsafe { jlong_to_pointer::<dom::Document>(this).as_ref().unwrap() };
A negative or 0 `this` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let node = u32::try_from(node_ref).expect("value beyond `u32` range");
A negative or 0 `node_ref` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let dom = unsafe { jlong_to_pointer::<dom::Document>(this).as_ref().unwrap() };
A negative or 0 `this` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let doc = unsafe { jlong_to_pointer::<dom::Document>(this).as_mut().unwrap() };
A negative or 0 `this` would cause this to panic that would need to be converted to a Java Exception.

2023-03-24 19:22 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    let other = unsafe { jlong_to_pointer::<dom::Document>(other).as_ref().unwrap() };
A negative or 0 `other` would cause this to panic that would need to be converted to a Java Exception.

2023-03-27 15:08 UTC, Kashif-E commented on jitpack.yml
> +  - yes | sdkmanager --uninstall "ndk-bundle" | sdkmanager --install "ndk;21.4.7075529"
https://github.com/jitpack/jitpack.io/issues/1776 this helped

2023-03-27 15:14 UTC, Kashif-E commented on jni_bindings/src/lib.rs
> +pub extern "system" fn Java_org_phoenixframework_liveview_lib_Document_00024Companion_initialize_1log<
he `00024` is a way to encode the $ symbol in the JNI function name.

When you have a companion object in a Kotlin class, the class will be compiled into a Java class with an inner static class named Companion, which is generated during the compilation process. JNI has a specific naming convention for method names, and since the $ symbol is not a valid character in JNI method names, it is replaced by `_00024.`

So, if you have a Kotlin class with a companion object like this:

```
class Document {
    companion object {
        @JvmStatic
        fun initializeLog() {
            // Some logic here
        }
    }
}
```
The corresponding JNI function name will be:

`Java_org_phoenixframework_liveview_lib_Document_00024Companion_initialize_1log`

2023-03-27 17:48 UTC, KronicDeth requested changes
I would try to get the cause out of the `Err` as you're losing the `expect` text like from `.expect("value beyond `u32` range")` by just having `"Rust panic occurred"` inside a `RuntimeException`.  Without including that message the exception reason isn't triagable without attaching a C-level debugger like gdb or lldb.

2023-03-28 21:21 UTC, Kashif-E commented
Update exception handling to contain the rust error message and  function name for better debugging

2023-03-29 17:25 UTC, KronicDeth approved these changes

2023-03-29 17:59 UTC, merged