Check for null pointers instead of relying on catch_unwind
liveview-native/liveview-native-core-jetpack pull request #3
Opened 2023-08-17 07:40 UTC by Bajix

This PR removes all usage of catch_unwind and instead checks for null pointers and throws the appropriate exceptions. All functions that rely on raw pointers have been updated to be marked as unsafe

2023-08-18 18:37 UTC, KronicDeth requested changes
The refcount functions need to be made thread safe

2023-08-18 18:37 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Document.kt
> +
This isn't thread-safe.  There's no `synchronized` or explicit mutex.

2023-08-25 14:13 UTC, nelson-glauber commented
From the Android standpoint, it's working fine using my development branch of [LiveView-Client-Jetpack](https://github.com/liveview-native/liveview-client-jetpack/tree/add-elixir-platform-lib).

2023-08-29 18:11 UTC, KronicDeth requested changes

2023-08-29 18:11 UTC, KronicDeth commented on core/build.gradle
> +}
Cool, I didn't know I could do that to get multiple tasks patched. ❤️

2023-08-29 18:11 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Attribute.kt
> +class Attribute internal constructor(private var nativeObject: Long) {
❤️ Good privacy change!

2023-08-29 18:11 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Document.kt
> +    private var asBorrow: Boolean
This can't change outside of the constructors, so it can be `val` instead of `var`

```suggestion
    private val asBorrow: Boolean
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Document
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.

```suggestion
    // raw pointer to Document
```

2023-08-29 18:11 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Document.kt
>      }
Doesn't this need to set `nativeObject = 0` like `delete` did, so `drop(nativeObject)`'s internal check for `this.is_null()` can work correctly in case some code calls `drop` twice?

2023-08-29 18:11 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/JavaResult.kt
> +internal class JavaResult(private var nativeObject: Long) {
❤️ Privacy change.

2023-08-29 18:11 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/JavaResult.kt
> +        drop(nativeObject)
Doesn't this need to set `nativeObject = 0` like `delete` did, so `drop(nativeObject)`'s internal check for `this.is_null()` can work correctly in case some code calls `drop` twice?

2023-08-29 18:11 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Node.kt
> +        }
This can remain a property with a getter defined

```suggestion
        val namespace: String
            get() = get_namespce(nativeOject)
```

2023-08-29 18:11 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Node.kt
> +        }
This can remain a property with a getter defined

```suggestion
        val tag: String
            get() = get_tag(nativeObject)
```

2023-08-29 18:11 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Node.kt
>          }
This can remain a property with a getter defined

```suggestion
        val attributes(): Array<Attribute>
            get() = get_attributes(nativeObject)
```

2023-08-29 18:11 UTC, KronicDeth commented on core/src/main/java/org/phoenixframework/liveview/lib/Node.kt
>          }
Doesn't this need to set `nativeObject = 0` like `delete` did, so `drop(nativeObject)`'s internal check for `this.is_null()` can work correctly in case some code calls `drop` twice?

2023-08-29 18:11 UTC, KronicDeth commented on core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt
> + */
```suggestion
```

2023-08-29 18:11 UTC, KronicDeth commented on core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt
> +        doc.merge(to,  Document.Companion.Handler());
It's not obvious how this test can fail.  What would happen if merge didn't work?

2023-08-29 18:11 UTC, KronicDeth commented on core/src/test/java/org/phoenixframework/liveview_jetpack/ExampleUnitTest.kt
> -package org.phoenixframework.liveview_jetpack
❤️

2023-08-29 18:11 UTC, KronicDeth commented on github.properties
> -## This file is automatically generated by Android Studio.
❤️

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to JavaResult
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.

```suggestion
    // raw pointer to JavaResult
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to JavaResult wrapping *mut Document
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.

```suggestion
    // raw pointer to JavaResult wrapping *mut Document
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to JavaResult
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.

```suggestion
    // raw pointer to JavaResult
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Document
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Document
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Document
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Document
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Document
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Node
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Node
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to node
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to node
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Element
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Element
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Element
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Element
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Element
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Element
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Element
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Element
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Attribute
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Attribute
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Attribute
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Attribute
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Attribute
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Attribute
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw-pointer to Attribute
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw-pointer to Attribute
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Document
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Document
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Document
The `non-null` can't be true or there would be no need for the `this.is_null()` check below.
```suggestion
    // raw pointer to Document
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to other Document
The `non-null` can't be true or there would be no need for the `other.is_null()` check below.
```suggestion
    // raw pointer to other Document
```

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +        .unwrap();
This error message should be improved to tell the caller which pointer was `null`.

2023-08-29 18:11 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +        let element = Box::new(node.data.element.clone());
The previous version did not clone the element.  This changes the semantics of the function.  Was this intentional?

2023-08-29 18:58 UTC, Bajix commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Document
Those changes are as a better means to prevent undefined behavior and to gracefully handle this exception because catch_unwind manages panics and not undefined behavior. If a null pointer is passed, this still will throw an exception, so it's documented this way because what is expected in the safety contract is a valid pointer.

2023-08-29 19:13 UTC, Bajix commented on core/src/main/java/org/phoenixframework/liveview/lib/Document.kt
>      }
Drop will never be called twice because it's private and finalize is by-design called at most once. The previous version of this was creating many Documents all with the same underlying native object pointer leading to each freeing the same native pointer causing the double free scenario which is now sidestepped by using asBorrow for Documents passed into callbacks to skip drop as an alternative to borrowing over FFI. I do have a borrow over FFI alternative but it wasn't stable when we tested and I changed course

2023-08-29 19:25 UTC, Bajix commented on jni_bindings/src/lib.rs
> +        let element = Box::new(node.data.element.clone());
Right so it might actually make more sense for me to update Element and Attribute to remove the Copy derive so that Clone must always be used which would make this change make more sense. I just didn't like the implicit copy of the prior version

2023-08-29 19:29 UTC, Bajix commented on core/build.gradle
> +}
Yea Nelson did a great job with this change overall; it was really not obvious how to fix this linking issue

2023-08-29 19:41 UTC, Bajix commented on jni_bindings/src/lib.rs
> +    // non-null raw pointer to Document
The rationale for documenting it this way is that it's an exception for a null pointer to be passed. The null check is to manage this exception in a way that is sound and doesn't rely on catch_rewind

2023-08-29 19:42 UTC, Bajix commented on core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt
> + */
I'm confused the commit suggestion interface says no changes were made

2023-08-29 19:44 UTC, Bajix commented on core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt
> +        doc.merge(to,  Document.Companion.Handler());
This test was to create a scenario in which a double free would occur without the asBorrow change

2023-08-29 20:34 UTC, KronicDeth commented on core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt
> + */
Redid it, it supposed to be to just delete the generated comment because it doesn't apply anymore.

2023-08-29 20:35 UTC, KronicDeth commented on core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt
> +        doc.merge(to,  Document.Companion.Handler());
So the test segfaults if the bug still exists?  Can we add a comment about that?

2023-08-29 20:51 UTC, KronicDeth requested changes

2023-08-29 20:51 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +    }
Here's a suggestion for a more specific error message

```suggestion
    let this_null = this.is_null();
    let other_null = other.is_null();
    
    if this_null() || other_null() {
        let message = String::new("Document::merged called with ");
        
        if this_null {
           message.push_str("null this pointer");
          
           if other_null {
              message.push_str(" and ");
            }
        }
        
        if other_null {
            message.push_str("null other pointer.");
        }
        
        env.throw_new(
            "java/lang/NullPointerException",
            message,
        )
        .unwrap();

        return;
    }
```

2023-08-29 21:03 UTC, KronicDeth commented on jni_bindings/src/lib.rs
> +        let message = match (this.is_null(), other.is_null()) {
Using a `match` was the other way I considered doing it.  I wasn't sure if having static strs was more important or 1 path for each part of the message.

2023-08-29 21:04 UTC, KronicDeth approved these changes

2023-08-29 21:06 UTC, Bajix commented on jni_bindings/src/lib.rs
> +        let message = match (this.is_null(), other.is_null()) {
Both ways work this just avoids the heap allocation overhead

2023-08-29 21:40 UTC, Bajix commented on core/src/test/java/org/phoenixframework/liveview_jetpack/DocumentTest.kt
> +        doc.merge(to,  Document.Companion.Handler());
Sure I'll add

2023-08-29 21:54 UTC, merged